name: JellyLegs
author: TheDiamondYT
version: 1.0.1
main: TheDiamondYT\JellyLegs\Main
api: [3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6 3.0.0-ALPHA7 3.0.0-ALPHA8 3.0.0-ALPHA9]
permissions:
    jellylegs.*:
        default: op
        description: Gives access to all JellyLegs permissions.
        children:
            jellylegs.toggle.self:
                default: op
                description: Allow use of the /jellylegs command on yourself.
            jellylegs.toggle.others:
                default: op
                description: Allow use of the /jellylegs command on others.
